#!/bin/bash

#tell grid engine to use current directory
#$ -cwd

case $# in
0)	RUNSTR="./CNmoonmars"
	;;
1)	RUNSTR="./CNmoonmars -gridRes $1"
	;;
2)  RUNSTR="./CNmoonmars -gridRes $1 -increment $2"
	;;
3)  RUNSTR="./CNmoonmars -gridRes $1 -increment $2 -interval $3"
	;;
4)  echo Error: Too many arguments. Exiting.
	set -e
	exit 1;
	;;
esac

exec > >(tee output/console-output.txt)
exec 2>&1

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo Running on:
hostname

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo Running \"make clean\":
make clean

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo Running \"make\":
make

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo Deleting files in \"output/\": 
rm `find output/* -type f | grep -v '^output/console-output.txt$'`
rm -r `find output/* -type d`

echo ---------------------------------------------------------------

echo Deleting files in \"status/\":
rm -r status/*

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo Running \"$RUNSTR\":
time $RUNSTR
