#!/bin/bash

#tell grid engine to use current directory
#$ -cwd

exec > >(tee output/console-output.txt)
exec 2>&1

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo Running on:
hostname

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo Running \"make clean\":
make clean

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo Running \"make\":
make

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo Deleting files in \"output/\": 
rm `find output/* -type f | grep -v '^output/console-output.txt$'`
rm -r `find output/* -type d`

echo ---------------------------------------------------------------

echo Deleting files in \"status/\":
rm -r status/*

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

RUNSTR="./CNmoonmars -gridres 10"
echo Running \"$RUNSTR\":
time $RUNSTR
